### ISSUE TITLE
FramesPerSecond, TimeCodesPerSecond, upAxis

### ISSUE THREAD

**Issue by chordee** [MoonShineVFX/reveries-config#213]
輸出有關 animation usd 時除了既有的請務必加上必要的 metadata
FramesPerSecond (fps) 
TimeCodesPerSecond（一般情況 - fps）
upAxis (Maya = Houdini = "Y")

[Transformations, Time-sampled Animation, and Layer Offsets](https://graphics.pixar.com/usd/docs/567231471.html)

否則不久的將來會發生災難性的錯誤
大概不會超過 one week...

**Comment by chordee** [comment]
[https://graphics.pixar.com/usd/docs/api/class_usd_stage.html#a8783e3ce37f5f9179ed0b6f3c51adcb0](https://graphics.pixar.com/usd/docs/api/class_usd_stage.html#a8783e3ce37f5f9179ed0b6f3c51adcb0)

[https://graphics.pixar.com/usd/docs/api/class_usd_stage.html#a1114e1f1e1d2f72fa68304ea44081765](https://graphics.pixar.com/usd/docs/api/class_usd_stage.html#a1114e1f1e1d2f72fa68304ea44081765)

**Comment by rebeccaLinx** [comment]
OK, 沒問題

**Comment by rebeccaLinx** [comment]
Added and released.
